#!/bin/sh
shout() { echo "package/compile: $@" >&2; }
barf() { shout "fatal: $@"; exit 111; }
safe() { "$@" || barf "cannot $@"; }
usage() {
  shout "usage: package/compile [ --help ] [ target ... ]"
  exit 100
}
####
umask 022
[ -d package ] || barf "no package directory"
[ -d src     ] || barf "no src directory"
here=`env - PATH=$PATH pwd`
#PATH="$here/compile:/command:$PATH"
#export PATH
#
[ "$1" = "--help" ] && usage
#
verbose="1"
if [ "$1" = "-v" ]
then
  shift
  verbose="$1"
  shift
fi
#
if [ $# -gt 0 ]
then
  safe package/build-run compile src compile "$@"
  safe package/build-command command compile `awk '
    BEGIN {
      for (i = 1;i < ARGC; ++i)
	file[ARGV[i]] = 1
      ARGC = 1
    }
    { if (file[$1]) print $1 }
  ' "$@" < package/commands`
else
  safe package/build-run compile src compile it
  safe package/build-command command compile `cat package/commands`
fi
exit 0
